# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ecc44ce
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
active: true
github_repo_name: boilercore
project_description: Common functionality of boiler repositories.
project_email: blake.naccarato@gmail.com
project_name: boilercore
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato, Kwang Jin Kim
project_version: 0.0.0
python_version: '3.11'
year_of_project_creation: 2023
