paths:
  scripts: data/scripts
  filt: data/scripts/filt.py
  csl: data/scripts/international-journal-of-heat-and-mass-transfer.csl
  template: data/scripts/template.dotx
  models: data/models
package_paths:
  stages:
    modelfun: src/boilercore/stages/modelfun.ipynb
