paths:
  project: .
  package: src/boilercore
  data: data
  stages:
    modelfun: src/boilercore/stages/modelfun.ipynb
  fit: src/boilercore/models/fit.py
  scripts: data/scripts
  filt: data/scripts/filt.py
  csl: data/scripts/international-journal-of-heat-and-mass-transfer.csl
  template: data/scripts/template.dotx
  model: data/model.dillpickle
