paths:
  scripts: scripts
  filt: scripts/filt.py
  csl: scripts/international-journal-of-heat-and-mass-transfer.csl
  template: scripts/template.dotx
  models: models
package_paths:
  stages:
    modelfun: stages/modelfun.ipynb
